### PR TITLE
RED-3229 - InfoSec additions

### PR DESCRIPTION
**Pull request by matthewbelisle-wf**
* Adding aviary.yaml
* Adding Dockerfile

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(3) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
<li>Watched keyword <code>ssl</code> in <code>aviary.yaml</code> line(s) ['4'] added</li>
<li>Watched keyword <code>SSL</code> in <code>aviary.yaml</code> line(s) ['5'] added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by ghost** [comment]
Security +1

**Comment by ericklaus-wf** [comment]
Do we need these things? I think RM is planning to override requirements for this repo, since this is expected to be short-lived fork.

**Comment by matthewbelisle-wf** [comment]
```
matthew.belisle   [11 minutes ago]
@teresa.revious Are you okay overriding the need for an aviary.yaml and the Dockerfile too since this repo is temporary? I’ve got https://github.com/Workiva/gh-ost/pull/3 up but I’m wondering if it’s not really needed. (edited)


teresa.revious   [2 minutes ago]
I am ok overriding it

teresa.revious   [2 minutes ago]
this is going to be the only release

matthew.belisle   [< 1 minute ago]
:thumbsup: Thanks
```

**Pull request closed without merging**
